[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
fastRerun = true

[client]
showErrorDetails = true

[mapbox]
token = ""  # Add Mapbox token if using maps
